package presenter;

public enum EVENTS {

       C_SHOW_DIALOG_ADD_CYCLIST, C_SHOW_TABLE_CYCLIST, C_SHOW_BEST_CYCLIST_GIRL, C_ADD_NEW_CYCLIST,C_SHOW_REPORT_FEMALE,
    C_SHOW_TABLE_AVERAGE, C_ENGLISH_LANGUAGE, C_SPANISH_LANGUAGE;
}
